@host = http://localhost:8080

### POST Good input
POST {{host}}/cards
Content-Type: application/json

{
  "cardNames": [
    "Lightning Bolt",
    "Black Lotus",
    "Counterspell"
  ]
}

> {%
  client.global.set("operationId", response.body.operationId);
%}

### POST Bad input
POST {{host}}/cards
Content-Type: application/json

{
  "cardNames": [
    "Lightning Bolt",
    "Black Lotvvvvvvvvus",
    "Counterspell",
    "pppppp",
    "Black Lotus",
    "aaaaa"
  ]
}

> {%
  client.global.set("operationId", response.body.operationId);
%}

### POST Really bad input
POST {{host}}/cards
Content-Type: application/json

{
  "cardNames": [
    "1",
    "2",
    "null",
    "exception",
    "3",
    4,
    "5",
    "6",
    "7",
    "7",
    "8",
    "9",
    "10"
  ]
}

> {%
  client.global.set("operationId", response.body.operationId);
%}

### GET Operation
GET {{host}}/cards/{{operationId}}
